***Types of Encoding***

*Nominal Encoding*
 Techniques : One hot encoding, One hot encoding with many categorical variables, Mean Encoding
*Ordinal Encoding*
 Techniques : Label Encoding, Target Guided Ordinal Encoding

**One hot Encoding**
No of unique lable  ==  No of colums added.
Dummy Variable Trap, always one column can detect if all column value is zero.
To need to avoid that the total new column is added ==> n-1

Disadvantage : Curse of Dimensionality

**Label Encoding**
give label to values respect to order.

**One hot Encoding With multiple Categories**
use only one hot encoding to top_10 categories.

**Target Guided Ordinal Categories**
feature and output
A 1
B 1
C 0
A 0
B 1
......

Find mean respect to categories
based on mean , assign rank to categories as labels

There is chance of data leakage , must use training data only to calculate mean.

**Mean Encoding**
feature and output
A 1
B 1
C 0
A 0
B 1
..
find mean each categorie
use that mean.

**Count / Frequency encoding**

multiple number of categories == high cardinality

Replace each label of the categorical variable by the count , this is the amount of times each label appears in the dataset.

simple to implement
does not increase curse of feature dimensionality

if some of the lables have the same coutn then they will ve replaced with same count and they loose some valuable information

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/mercedesbenz.csv',usecols=['X1'])
df

     X1
0     v
1     t
2     w
3     t
4     v
...  ..
4204  s
4205  o
4206  v
4207  r
4208  r

[4209 rows x 1 columns]

In [3]:
data_dict = df.X1.value_counts().to_dict()

In [4]:
data_dict

{'aa': 833,
 's': 598,
 'b': 592,
 'l': 590,
 'v': 408,
 'r': 251,
 'i': 203,
 'a': 143,
 'c': 121,
 'o': 82,
 'w': 52,
 'z': 46,
 'u': 37,
 'e': 33,
 'm': 32,
 't': 31,
 'h': 29,
 'y': 23,
 'f': 23,
 'j': 22,
 'n': 19,
 'k': 17,
 'p': 9,
 'g': 6,
 'd': 3,
 'q': 3,
 'ab': 3}

In [9]:
df['X1'] = df['X1'].map(data_dict)
df.head()

   X1
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN

**Probability Ratio Encoding**

Also called Odds Ratio Encoding.

Instead of:

One-Hot Encoding

Label Encoding

We replace each category with:


P(Not Survived | Category)
divide
P(Survived | Category)
	​
Why Use It?

Because it captures:

“How strongly this category is associated with survival?”

Instead of creating many dummy columns.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data/titanic.csv',usecols=['Cabin','Survived'])
df.head()

   Survived Cabin
0         0   NaN
1         1   C85
2         1   NaN
3         1  C123
4         0   NaN

In [5]:
df['Cabin'] = df['Cabin'].fillna('Missing')
df.head()

   Survived    Cabin
0         0  Missing
1         1      C85
2         1  Missing
3         1     C123
4         0  Missing

In [6]:
df['Cabin'].unique()

<StringArray>
[    'Missing',         'C85',        'C123',         'E46',          'G6',
        'C103',         'D56',          'A6', 'C23 C25 C27',         'B78',
 ...
        'B102',         'B69',         'E49',         'C47',         'D28',
         'E17',         'A24',         'C50',         'B42',        'C148']
Length: 148, dtype: str

In [7]:
df['Cabin'] = df['Cabin'].astype(str).str[0]
df.head()

   Survived Cabin
0         0     M
1         1     C
2         1     M
3         1     C
4         0     M

In [8]:
df.Cabin.unique()

<StringArray>
['M', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T']
Length: 9, dtype: str

In [9]:
prod_df = df.groupby(['Cabin'])['Survived'].mean()
prod_df

Cabin
A    0.466667
B    0.744681
C    0.593220
D    0.757576
E    0.750000
F    0.615385
G    0.500000
M    0.299854
T    0.000000
Name: Survived, dtype: float64

In [10]:
prod_df = pd.DataFrame(prod_df)
prod_df

       Survived
Cabin
A      0.466667
B      0.744681
C      0.593220
D      0.757576
E      0.750000
F      0.615385
G      0.500000
M      0.299854
T      0.000000

In [11]:
prod_df['Died'] = 1 - prod_df['Survived']
prod_df.head()

       Survived      Died
Cabin
A      0.466667  0.533333
B      0.744681  0.255319
C      0.593220  0.406780
D      0.757576  0.242424
E      0.750000  0.250000

In [12]:
prod_df['Probability_ratio'] = prod_df['Survived']/prod_df['Died']
prod_df.head()

       Survived      Died  Probability_ratio
Cabin
A      0.466667  0.533333           0.875000
B      0.744681  0.255319           2.916667
C      0.593220  0.406780           1.458333
D      0.757576  0.242424           3.125000
E      0.750000  0.250000           3.000000

In [13]:
prob_encode = prod_df['Probability_ratio'].to_dict()
prob_encode

{'A': 0.875,
 'B': 2.916666666666666,
 'C': 1.4583333333333333,
 'D': 3.125,
 'E': 3.0,
 'F': 1.6000000000000003,
 'G': 1.0,
 'M': 0.42827442827442824,
 'T': 0.0}

In [14]:
df['Cabin_encoded'] = df['Cabin'].map(prob_encode) 
df.head()

   Survived Cabin  Cabin_encoded
0         0     M       0.428274
1         1     C       1.458333
2         1     M       0.428274
3         1     C       1.458333
4         0     M       0.428274