In [4]:
import numpy as np
import pandas as pd

In [5]:
data = pd.read_csv('data/orders.csv')
time = pd.read_csv('data/messages.csv')

In [6]:
data.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [7]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

## working with dates

In [8]:
data['date'] = pd.to_datetime(data['date'])

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

In [11]:
data['year'] = data['date'].dt.year

In [12]:
data['month'] = data['date'].dt.month

In [13]:
data['month_name'] = data['date'].dt.month_name()

In [14]:
data['days'] = data['date'].dt.day

In [15]:
data['day_of_week'] = data['date'].dt.day_of_week

In [16]:
data['dow_name'] = data['date'].dt.day_name()

In [17]:
data['isweekend'] = np.where(data['dow_name'].isin(['Sunday','Saturday']),1,0)

In [20]:
data['weekofyear'] = data['date'].dt.weekday

In [22]:
data['quarter'] = data['date'].dt.quarter

In [25]:
data['semester'] = np.where(data['quarter'].isin([1,2]), 1, 2)

In [26]:
data.head()

,date,product_id,city_id,orders,year,month,month_name,days,day_of_week,dow_name,isweekend,weekofyear,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,1,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,2,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,1,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,5,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,6,1,1

## Extract Time elapsed between dates

In [27]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 2, 28, 15, 7, 14, 512979)

In [29]:
today - data['date']

0     2272 days 15:07:14.512979
1     2754 days 15:07:14.512979
2     2685 days 15:07:14.512979
3     2387 days 15:07:14.512979
4     2610 days 15:07:14.512979
                 ...
995   2700 days 15:07:14.512979
996   2641 days 15:07:14.512979
997   2489 days 15:07:14.512979
998   2554 days 15:07:14.512979
999   2328 days 15:07:14.512979
Name: date, Length: 1000, dtype: timedelta64[us]

In [30]:
(today - data['date']).dt.days

0      2272
1      2754
2      2685
3      2387
4      2610
       ...
995    2700
996    2641
997    2489
998    2554
999    2328
Name: date, Length: 1000, dtype: int64

In [31]:
# Months passed

np.round((today -data['date']) / np.timedelta64(1, 'M'),0)

ValueError: Unit M is not supported. Only unambiguous timedelta values durations are supported. Allowed units are 'W', 'D', 'h', 'm', 's', 'ms', 'us', 'ns'

In [32]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [33]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [34]:
time['date'].dt.time

0      00:50:00
1      23:40:00
2      00:21:00
3      00:31:00
4      23:11:00
         ...
995    00:50:00
996    23:14:00
997    23:37:00
998    23:34:00
999    23:25:00
Name: date, Length: 1000, dtype: object